export const PRODUCTS_ACTION_TYPES = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
  SET_CHECKED_DISCOUNTS_FILTER: "SET_CHECKED_DISCOUNTS_FILTER",
  SET_PRICE_FILTER: "SET_PRICE_FILTER",
  SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
  ADD_PRODUCT: "ADD_PRODUCT",
};
