export const USER_ACTION_TYPES = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  SET_ALL_USERS: "SET_ALL_USERS",
  SET_PRODUCT_IN_CART: "SET_PRODUCT_IN_CART",
  CLEAR_CART: "CLEAR_CART",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  ADD_PRODUCT_TO_FAVORITES: "ADD_PRODUCT_TO_FAVORITES",
  REMOVE_PRODUCT_FROM_FAVORITES: "REMOVE_PRODUCT_FROM_FAVORITES",
  GET_ALL_FAVORITES_FROM_API: "GET_ALL_FAVORITES_FROM_API",
  CLEAR_REDUX_USER_FAVORITES: "CLEAR_REDUX_USER_FAVORITES",
};
